apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
spec:
  replicas: 3
  selector:
    matchLabels: 
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
        - name: myapp
          image: nginx
